# Generated by Django 4.1.7 on 2023-04-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zadanie_po_kursu_2', '0002_alter_user_pin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_user',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
