# Generated by Django 4.1.7 on 2023-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zadanie_po_kursu_2', '0003_user_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='eur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='rub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='usd',
            field=models.IntegerField(default=0),
        ),
    ]
