# Generated by Django 4.1.7 on 2023-04-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zadanie_po_kursu_2', '0004_alter_balance_eur_alter_balance_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zadanie_po_kursu_2.user'),
        ),
    ]
