# Generated by Django 4.1.7 on 2023-03-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual_work_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='individual_work_2.department'),
        ),
    ]
